### ISSUE TITLE
Recent "yanking" of fastlane_core 0.60.0 causes dependency issue with watchbuild

### ISSUE THREAD

**Issue by lemonkey** [fastlane/watchbuild#1]
> Bundler could not find compatible versions for gem "fastlane_core":
>   In Gemfile:
>     fastlane_core (= 1.0.0)
> 
>     watchbuild (= 0.1.4) was resolved to 0.1.4, which depends on
>       fastlane_core (< 1.0.0, >= 0.43.1)

My Gemfile currently has 0.1.4 defined as it's the latest version.

However, I'm currently being forced to point to fastlane_core 1.0.0 in my Gemfile since if I don't, it will try to find 0.60.0 which has recently been yanked from [rubygems.org](https://rubygems.org/gems/fastlane_core/versions/0.60.0):

> This version has been yanked, and it is not available for download directly or for other gems that may have depended on it.
> 
> VERSIONS:
> 1.0.0 - December 18, 2016 (44 KB)
> 0.59.0 - December 7, 2016 (43.5 KB)
> 0.58.0 - December 5, 2016 (43 KB)
> 0.57.2 - November 29, 2016 (43 KB)
> 0.57.1 - November 23, 2016 (43 KB)

**Comment by lemonkey** [comment]
I could obviously remove watchbuild from the Gemfile but that's not ideal for my situation long term.

**Comment by milch** [comment]
Hi @lemonkey, I just released a new version of watchbuild ([0.2.0](https://github.com/fastlane/watchbuild/releases/tag/0.2.0)) that should fix your error. Sorry about that! 

I'm going to close this now, so just let me know if it's still not working for you after this and we'll reopen it!
