### ISSUE TITLE
watchbuild v0.1.1 fails with "undefined local variable 'v'"

### ISSUE THREAD

**Issue by tmm1** [fastlane/watchbuild#1]
```
[15:25:22]: Successfully logged in
[15:25:23]: undefined local variable or method `v' for #<WatchBuild::Runner:0x007f8019265cc8>
[15:25:23]: Something failed... trying again to recover
```

**Comment by tmm1** [comment]
undefined variable here: https://github.com/fastlane/watchbuild/blob/master/lib/watchbuild/runner.rb#L71

**Comment by tmm1** [comment]
I guess the underlying issue here is that only ios builds are supported and I'm trying to watch a tvos build.

**Comment by mergesort** [comment]
I'm getting this too when I don't have any builds in processing. It should probably just log that instead of throwing an error.

**Comment by shirkan** [comment]
I get that too when I have no builds. Will that notify me when I'll upload builds?

**Comment by asfalcone** [comment]
Hi All, is this still an issue with 0.1.3?
