### ISSUE TITLE
Could not find action or lane 'watchbuild'.

### ISSUE THREAD

**Issue by biolinh** [fastlane/watchbuild#15]
Hi 
I want to use watchbuild to notify me when my new binary finish processing process so in the fastfane file  as below:

```
lane :beta do
    increment_build_number
   gym(scheme: "myapp") # Build your app - more options available
    pilot(skip_submission: true)
    watchbuild
end
```

Then I run:  `fastlane beta`

But, I get the error:
```
Could not find action or lane 'watchbuild'. Check out the README for more details: https://github.com/fastlane/fastlane
fast_file.rb:141:in `rescue in method_missing'
fastlane/fast_file.rb:136:in `method_missing'
Fastfile:62:in `block (2 levels) in parsing_binding'
```
However, I run watchbuild in my terminal at project's root , it run ok and push notification on my laptop. 

Therefore, my question is I can add "watchbuild" in fastlane file or I don't add  "watchbuild" in fastlane file and run as follow:

`$ fastlane beta `
`$ watchbuild `

If I can add it in fastlane, what should I do to fix it?

**Comment by vpolouchkine** [comment]
It's failing because there is no specific action for that tool, but you can invoke it like this (in the Fastfile): 

```ruby
sh "watchbuild"
```

**Comment by biolinh** [comment]
@vpolouchkine 
oh, Thanks you. It is ok.
