### ISSUE TITLE
undefined method `this' for #<Gem::Specification:0x3fd3a403cbb0 json-2.0.2>

### ISSUE THREAD

**Issue by aleufms** [fastlane/watchbuild#2]
Are there someone with this error?

> /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd3a403cbb0 json-2.0.2> (NoMethodError)
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/gems/fastlane-2.8.0/fastlane_core/lib/fastlane_core.rb:1:in `<top (required)>'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/gems/watchbuild-0.2.0/lib/watchbuild/options.rb:1:in `<top (required)>'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/gems/watchbuild-0.2.0/lib/watchbuild.rb:2:in `<top (required)>'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/an/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/gems/watchbuild-0.2.0/bin/watchbuild:5:in `<top (required)>'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/bin/watchbuild:22:in `load'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/bin/watchbuild:22:in `<main>'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
> 	from /Users/an/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by aleufms** [comment]
Updating to json 2.0.3 resolved the issue.

**Comment by KrauseFx** [comment]
Yeah 👍
