### ISSUE TITLE
Run in background process

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/watchbuild#4]
I would personally love to have this run in the background and let me know so I don't have to remember to invoke this or alternatively invoke this as part of fastlane

**Comment by jonas-andersson-stratsys** [comment]
Agrees

**Comment by ffittschen** [comment]
+1
It would also be nice to have the possibility to post to a slack channel. I always overlook those desktop notifications

**Comment by mathiasAichinger** [comment]
Today I have started with a server, because I want to trigger it from fastlane, but I don't want to wait until the build is processed for a successful build.
